<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>[=groupId]</groupId>
    <artifactId>[=artifactId]</artifactId>
    <version>[=version]</version>

    <name>[=name]</name>
    <description>[=description]</description>

    <properties>
        <release>[=release]</release>
        <lineCoverage>0.95</lineCoverage>
        <branchCoverage>0.88</branchCoverage>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jdk.version>1.7</jdk.version>
        <platform.version>7.0.8</platform.version>
        <business-hub-core.version>2.2.5</business-hub-core.version>
        <business-hub.version>2.2.4</business-hub.version>
        <ru-sbrf-bh-banking-product.version>3.1.5</ru-sbrf-bh-banking-product.version>
        <thirdparty.activemq.version>5.13.0</thirdparty.activemq.version>
        <powermock.version>1.6.6</powermock.version>
        <powermock.api.version>1.7.0RC2</powermock.api.version>
        <jacoco.version>0.8.0</jacoco.version>
        <maven.compiler.plugin.version>3.1</maven.compiler.plugin.version>
        <skip.report>true</skip.report>
        <sonar.coverage.exclusions>
            **/classifier/*.*,
            **/enumerations/audit/**,
            **/enumerations/ContactType.*,
            **/exception/*.*,
            **/status/*.*,
            **/vo/**
        </sonar.coverage.exclusions>
        <com.ibm.version>7.5</com.ibm.version>
    </properties>

    <!-- scm>
        <connection>scm:git:ssh://git@stash.ca.sbrf.ru:7999/sbrf/ru.sbrf.bh.banking.product.smbaccounting.git
        </connection>
        <developerConnection>scm:git:ssh://git@stash.ca.sbrf.ru:7999/sbrf/ru.sbrf.bh.banking.product.smbaccounting.git
        </developerConnection>
        <tag>HEAD</tag>
        <url>https://stash.ca.sbrf.ru/projects/SBRF/repos/ru.sbrf.bh.banking.product.smbaccounting</url>
    </scm -->

    <dependencies>
        <!-- UFS platform -->
        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-runtime</artifactId>
            <version>${platform.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-core</artifactId>
            <version>${platform.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-testing</artifactId>
            <version>${platform.version}</version>
            <type>pom</type>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>jetty</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- UAM -->
        <dependency>
            <groupId>ru.sbrf.efs.model</groupId>
            <artifactId>business-hub</artifactId>
            <version>${business-hub.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sbrf.efs.model</groupId>
            <artifactId>business-hub-core</artifactId>
            <version>${business-hub-core.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sbrf.efs.app</groupId>
            <artifactId>ru.sbrf.bh.banking.product</artifactId>
            <version>${ru-sbrf-bh-banking-product.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sbrf.efs.integration.*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax</groupId>
                    <artifactId>javaee-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ru.sbrf.efs.app</groupId>
                    <artifactId>ru.sbrf.bh.banking.callstate</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- Integration 2.0-->
        <dependency>
            <groupId>ru.sbrf.ufs.integration</groupId>
            <artifactId>integration-module</artifactId>
            <version>1.0.12</version>
        </dependency>

        <#list adapters as adapter>
        <dependency>
            <groupId>[=adapter.groupId]</groupId>
            <artifactId>[=adapter.artifactId]</artifactId>
            <version>[=adapter.version]</version>
        </dependency>
        </#list>

        <!-- IBM -->
        <dependency>
            <groupId>com.ibm</groupId>
            <artifactId>com.ibm.mqjms</artifactId>
            <version>${com.ibm.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm</groupId>
            <artifactId>com.ibm.mq.headers</artifactId>
            <version>${com.ibm.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm.websphere</groupId>
            <artifactId>ogclient</artifactId>
            <version>8.6.0.8</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm.mq.client</groupId>
            <artifactId>com.ibm.mq</artifactId>
            <version>${com.ibm.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm</groupId>
            <artifactId>com.ibm.mq.jmqi</artifactId>
            <version>${com.ibm.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm.disthub2</groupId>
            <artifactId>dhbcore</artifactId>
            <version>${com.ibm.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- Other -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-testng</artifactId>
            <version>${powermock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <version>${powermock.api.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>org.jacoco.agent</artifactId>
            <classifier>runtime</classifier>
            <version>${jacoco.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>javax.jms</groupId>
            <artifactId>javax.jms-api</artifactId>
            <version>2.0.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>check-coverage</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <configuration>
                            <excludes>${sonar.coverage.exclusions}</excludes>
                        </configuration>
                        <executions>
                            <execution>
                                <id>default-instrument</id>
                                <goals>
                                    <goal>instrument</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-restore-instrumented-classes</id>
                                <goals>
                                    <goal>restore-instrumented-classes</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>post-unit-test</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                                <configuration>
                                    <dataFile>${project.build.directory}/coverage-reports/jacoco-ut.exec</dataFile>
                                    <outputDirectory>${project.build.directory}/site</outputDirectory>
                                    <skip>${skip.report}</skip>
                                </configuration>
                            </execution>
                            <execution>
                                <id>default-check</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                                <configuration>
                                    <dataFile>${project.build.directory}/coverage-reports/jacoco-ut.exec</dataFile>
                                    <rules>
                                        <rule>
                                            <limits>
                                                <limit>
                                                    <counter>INSTRUCTION</counter>
                                                    <value>COVEREDRATIO</value>
                                                    <minimum>${lineCoverage}</minimum>
                                                </limit>
                                                <limit>
                                                    <counter>BRANCH</counter>
                                                    <value>COVEREDRATIO</value>
                                                    <minimum>${branchCoverage}</minimum>
                                                </limit>
                                            </limits>
                                        </rule>
                                    </rules>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>sonar-coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <configuration>
                            <excludes>${sonar.coverage.exclusions}</excludes>
                        </configuration>
                        <executions>
                            <execution>
                                <id>default-instrument</id>
                                <goals>
                                    <goal>instrument</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-restore-instrumented-classes</id>
                                <goals>
                                    <goal>restore-instrumented-classes</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>post-unit-test</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                                <configuration>
                                    <dataFile>${project.build.directory}/coverage-reports/jacoco-ut.exec</dataFile>
                                    <outputDirectory>${project.build.directory}/site</outputDirectory>
                                </configuration>
                            </execution>
                            <execution>
                                <id>pre-integration-test</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>prepare-agent-integration</goal>
                                </goals>
                                <configuration>
                                    <destFile>${project.build.directory}/coverage-reports/jacoco-it.exec</destFile>
                                    <propertyName>integrationTestArgLine</propertyName>
                                </configuration>
                            </execution>
                            <execution>
                                <id>post-integration-test</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>report-integration</goal>
                                </goals>
                                <configuration>
                                    <dataFile>${project.build.directory}/coverage-reports/jacoco-it.exec</dataFile>
                                    <outputDirectory>${project.build.directory}/jacoco-it-report</outputDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${jdk.version}</source>
                    <target>${jdk.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.15</version>
                <configuration>
                    <forkCount>1.5C</forkCount>
                    <reuseForks>true</reuseForks>
                    <systemPropertyVariables>
                        <jacoco-agent.destfile>${project.build.directory}/coverage-reports/jacoco-ut.exec
                        </jacoco-agent.destfile>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.6</version>
                <executions>
                    <execution>
                        <id>test</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>testResources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/test-classes</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.0.0-M1</version>
                <configuration>
                    <show>private</show>
                    <nohelp>true</nohelp>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <phase>install</phase>
                        <configuration>
                            <doctitle>API for ${project.name} ${project.version}</doctitle>
                            <windowtitle>API for ${project.name} ${project.version}</windowtitle>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <id>vo-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classifier>vo</classifier>
                            <includes>
                                <include>**/classifier/*.class</include>
                                <include>**/enumerations/**</include>
                                <include>**/exception/*.class</include>
                                <include>**/status/*.class</include>
                                <include>**/vo/**</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <snapshotRepository>
            <id>nexus-alpha-snapshots</id>
            <url>http://sbtnexus.ca.sbrf.ru:8081/nexus/content/repositories/efs_snapshot/</url>
        </snapshotRepository>
        <repository>
            <id>nexus-alpha-release</id>
            <url>http://sbtnexus.ca.sbrf.ru:8081/nexus/content/repositories/efs_release</url>
        </repository>
    </distributionManagement>
</project>